### ISSUE TITLE
Enhanced go-do-def

### ISSUE THREAD

**Issue by antonk52** [antonk52/coc-protobuf#1]
## TODO:
- [ ] support for Service go-to-def
- [ ] support for Enum go-to-def
- [ ] support for nested message definitions

## Useful links
- [Protobuf spec](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#message_definition)
- [protobufjs](https://www.npmjs.com/package/protobufjs)
